export const EJECUCION_DATA = [
  {
    renglon: 111,
    descripcion: "ENERGÍA ELÉCTRICA",
    subProducto: "001-001-0001",
    nuevoVigente: 21000,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 112,
    descripcion: "AGUA",
    subProducto: "001-001-0001",
    nuevoVigente: 350,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 113,
    descripcion: "TELEFONÍA",
    subProducto: "001-001-0001",
    nuevoVigente: 39172,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 114,
    descripcion: "CORREOS Y TELÉGRAFOS",
    subProducto: "001-001-0001",
    nuevoVigente: 1600,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 115,
    descripcion: "EXTRACCIÓN DE BASURA Y DESTRUCCIÓN DE DESECHOS SÓLIDOS",
    subProducto: "001-001-0001",
    nuevoVigente: 1992,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 122,
    descripcion: "IMPRESIÓN, ENCUADERNACIÓN Y REPRODUCCIÓN",
    subProducto: "001-001-0001",
    nuevoVigente: 2000,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 133,
    descripcion: "VIÁTICOS EN EL INTERIOR",
    subProducto: "001-001-0001",
    nuevoVigente: 40000,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 135,
    descripcion: "OTROS VIÁTICOS Y GASTOS CONEXOS",
    subProducto: "001-001-0001",
    nuevoVigente: 30000,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 141,
    descripcion: "TRANSPORTE DE PERSONAS",
    subProducto: "001-001-0001",
    nuevoVigente: 30000,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 151,
    descripcion: "ARRENDAMIENTO DE EDIFICIOS Y LOCALES",
    subProducto: "001-001-0001",
    nuevoVigente: 175000,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 157,
    descripcion: "ARRENDAMIENTO DE EQUIPO DE CÓMPUTO",
    subProducto: "001-001-0001",
    nuevoVigente: 28125,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 158,
    descripcion: "DERECHOS DE BIENES INTANGIBLES",
    subProducto: "001-001-0001",
    nuevoVigente: 181911,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 171,
    descripcion: "MANTENIMIENTO Y REPARACIÓN DE EDIFICIOS",
    subProducto: "001-001-0001",
    nuevoVigente: 360000,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 174,
    descripcion: "MANTENIMIENTO Y REPARACIÓN DE INSTALACIONES",
    subProducto: "001-001-0001",
    nuevoVigente: 290000,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 182,
    descripcion: "SERVICIOS MÉDICO-SANITARIOS",
    subProducto: "001-003-0001",
    nuevoVigente: 47000,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 182,
    descripcion: "SERVICIOS MÉDICO-SANITARIOS",
    subProducto: "001-003-0005",
    nuevoVigente: 18000,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 182,
    descripcion: "SERVICIOS MÉDICO-SANITARIOS",
    subProducto: "001-004-0001",
    nuevoVigente: 760074,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 182,
    descripcion: "SERVICIOS MÉDICO-SANITARIOS",
    subProducto: "001-004-0004",
    nuevoVigente: 128795,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 182,
    descripcion: "SERVICIOS MÉDICO-SANITARIOS",
    subProducto: "001-005-0001",
    nuevoVigente: 14705,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 182,
    descripcion: "SERVICIOS MÉDICO-SANITARIOS",
    subProducto: "001-005-0003",
    nuevoVigente: 7001,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 182,
    descripcion: "SERVICIOS MÉDICO-SANITARIOS",
    subProducto: "001-008-0002",
    nuevoVigente: 7200,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 182,
    descripcion: "SERVICIOS MÉDICO-SANITARIOS",
    subProducto: "001-008-0003",
    nuevoVigente: 11200,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 182,
    descripcion: "SERVICIOS MÉDICO-SANITARIOS",
    subProducto: "001-008-0004",
    nuevoVigente: 28000,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 182,
    descripcion: "SERVICIOS MÉDICO-SANITARIOS",
    subProducto: "001-010-0001",
    nuevoVigente: 9794,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 182,
    descripcion: "SERVICIOS MÉDICO-SANITARIOS",
    subProducto: "001-018-0001",
    nuevoVigente: 6000,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 182,
    descripcion: "SERVICIOS MÉDICO-SANITARIOS",
    subProducto: "001-019-0001",
    nuevoVigente: 200637,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 182,
    descripcion: "SERVICIOS MÉDICO-SANITARIOS",
    subProducto: "001-020-0001",
    nuevoVigente: 9774,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 182,
    descripcion: "SERVICIOS MÉDICO-SANITARIOS",
    subProducto: "003-005-0004",
    nuevoVigente: 60452,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 186,
    descripcion: "SERVICIOS DE INFORMÁTICA Y SISTEMAS COMPUTARIZADOS",
    subProducto: "001-001-0001",
    nuevoVigente: 80357,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 189,
    descripcion: "OTROS ESTUDIOS Y/O SERVICIOS",
    subProducto: "001-001-0001",
    nuevoVigente: 80357,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 199,
    descripcion: "OTROS SERVICIOS",
    subProducto: "001-001-0001",
    nuevoVigente: 22185,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 211,
    descripcion: "ALIMENTOS PARA PERSONAS",
    subProducto: "001-001-0001",
    nuevoVigente: 1500,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 211,
    descripcion: "ALIMENTOS PARA PERSONAS",
    subProducto: "001-004-0001",
    nuevoVigente: 5600,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 211,
    descripcion: "ALIMENTOS PARA PERSONAS",
    subProducto: "001-004-0004",
    nuevoVigente: 900,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 211,
    descripcion: "ALIMENTOS PARA PERSONAS",
    subProducto: "001-019-0001",
    nuevoVigente: 5600,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 211,
    descripcion: "ALIMENTOS PARA PERSONAS",
    subProducto: "003-005-0001",
    nuevoVigente: 900,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 211,
    descripcion: "ALIMENTOS PARA PERSONAS",
    subProducto: "003-005-0004",
    nuevoVigente: 4880,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 233,
    descripcion: "PRENDAS DE VESTIR",
    subProducto: "001-001-0001",
    nuevoVigente: 10860,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 241,
    descripcion: "PAPEL DE ESCRITORIO",
    subProducto: "001-001-0001",
    nuevoVigente: 4900,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 242,
    descripcion: "PAPELES COMERCIALES, CARTULINAS, CARTONES Y OTROS",
    subProducto: "001-005-0001",
    nuevoVigente: 500,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 242,
    descripcion: "PAPELES COMERCIALES, CARTULINAS, CARTONES Y OTROS",
    subProducto: "001-019-0001",
    nuevoVigente: 250,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 243,
    descripcion: "PRODUCTOS DE PAPEL O CARTÓN",
    subProducto: "001-001-0001",
    nuevoVigente: 6336,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 244,
    descripcion: "PRODUCTOS DE ARTES GRÁFICAS",
    subProducto: "001-001-0001",
    nuevoVigente: 3909,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 247,
    descripcion: "ESPECIES TIMBRADAS Y VALORES",
    subProducto: "001-001-0001",
    nuevoVigente: 300,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 252,
    descripcion: "ARTÍCULOS DE CUERO",
    subProducto: "001-001-0001",
    nuevoVigente: 1566,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 261,
    descripcion: "ELEMENTOS Y COMPUESTOS QUÍMICOS",
    subProducto: "001-001-0001",
    nuevoVigente: 3250,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 261,
    descripcion: "ELEMENTOS Y COMPUESTOS QUÍMICOS",
    subProducto: "001-004-0001",
    nuevoVigente: 148,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 261,
    descripcion: "ELEMENTOS Y COMPUESTOS QUÍMICOS",
    subProducto: "001-005-0001",
    nuevoVigente: 18,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 261,
    descripcion: "ELEMENTOS Y COMPUESTOS QUÍMICOS",
    subProducto: "001-005-0003",
    nuevoVigente: 18,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 261,
    descripcion: "ELEMENTOS Y COMPUESTOS QUÍMICOS",
    subProducto: "001-010-0001",
    nuevoVigente: 9,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 261,
    descripcion: "ELEMENTOS Y COMPUESTOS QUÍMICOS",
    subProducto: "001-013-0001",
    nuevoVigente: 9,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 261,
    descripcion: "ELEMENTOS Y COMPUESTOS QUÍMICOS",
    subProducto: "001-013-0002",
    nuevoVigente: 9,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 261,
    descripcion: "ELEMENTOS Y COMPUESTOS QUÍMICOS",
    subProducto: "001-019-0001",
    nuevoVigente: 148,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 261,
    descripcion: "ELEMENTOS Y COMPUESTOS QUÍMICOS",
    subProducto: "001-020-0001",
    nuevoVigente: 9,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 262,
    descripcion: "COMBUSTIBLES Y LUBRICANTES",
    subProducto: "001-001-0001",
    nuevoVigente: 1200,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 266,
    descripcion: "PRODUCTOS MEDICINALES Y FARMACÉUTICOS",
    subProducto: "001-004-0001",
    nuevoVigente: 436777,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 266,
    descripcion: "PRODUCTOS MEDICINALES Y FARMACÉUTICOS",
    subProducto: "001-004-0004",
    nuevoVigente: 14690,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 266,
    descripcion: "PRODUCTOS MEDICINALES Y FARMACÉUTICOS",
    subProducto: "001-005-0001",
    nuevoVigente: 11950,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 266,
    descripcion: "PRODUCTOS MEDICINALES Y FARMACÉUTICOS",
    subProducto: "001-005-0003",
    nuevoVigente: 3957,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 266,
    descripcion: "PRODUCTOS MEDICINALES Y FARMACÉUTICOS",
    subProducto: "001-010-0001",
    nuevoVigente: 1280,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 266,
    descripcion: "PRODUCTOS MEDICINALES Y FARMACÉUTICOS",
    subProducto: "001-012-0001",
    nuevoVigente: 2850,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 266,
    descripcion: "PRODUCTOS MEDICINALES Y FARMACÉUTICOS",
    subProducto: "001-012-0002",
    nuevoVigente: 128,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 266,
    descripcion: "PRODUCTOS MEDICINALES Y FARMACÉUTICOS",
    subProducto: "001-013-0001",
    nuevoVigente: 1978,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 266,
    descripcion: "PRODUCTOS MEDICINALES Y FARMACÉUTICOS",
    subProducto: "001-013-0002",
    nuevoVigente: 768,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 266,
    descripcion: "PRODUCTOS MEDICINALES Y FARMACÉUTICOS",
    subProducto: "001-019-0001",
    nuevoVigente: 279651,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 266,
    descripcion: "PRODUCTOS MEDICINALES Y FARMACÉUTICOS",
    subProducto: "001-020-0001",
    nuevoVigente: 1520,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 266,
    descripcion: "PRODUCTOS MEDICINALES Y FARMACÉUTICOS",
    subProducto: "003-005-0001",
    nuevoVigente: 6288,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 266,
    descripcion: "PRODUCTOS MEDICINALES Y FARMACÉUTICOS",
    subProducto: "003-005-0002",
    nuevoVigente: 580,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 266,
    descripcion: "PRODUCTOS MEDICINALES Y FARMACÉUTICOS",
    subProducto: "003-005-0004",
    nuevoVigente: 11080,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 267,
    descripcion: "TINTES, PINTURAS Y COLORANTES",
    subProducto: "001-001-0001",
    nuevoVigente: 22000,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 268,
    descripcion: "PRODUCTOS PLÁSTICOS, NYLON, VINIL Y P.V.C.",
    subProducto: "001-001-0001",
    nuevoVigente: 78195,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 269,
    descripcion: "OTROS PRODUCTOS QUÍMICOS Y CONEXOS",
    subProducto: "001-001-0001",
    nuevoVigente: 800,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 283,
    descripcion: "PRODUCTOS DE METAL Y SUS ALEACIONES",
    subProducto: "001-001-0001",
    nuevoVigente: 600,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 289,
    descripcion: "OTROS PRODUCTOS METÁLICOS",
    subProducto: "001-001-0001",
    nuevoVigente: 13500,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 291,
    descripcion: "ÚTILES DE OFICINA",
    subProducto: "001-001-0001",
    nuevoVigente: 28466,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 292,
    descripcion: "PRODUCTOS SANITARIOS, DE LIMPIEZA Y DE USO PERSONAL",
    subProducto: "001-001-0001",
    nuevoVigente: 9375,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 295,
    descripcion: "ÚTILES MENORES, SUMINISTROS E INSTRUMENTAL MÉDICO-QUIRÚRGICOS, DE LABORATORIO Y CUIDADO DE LA SALUD",
    subProducto: "001-004-0001",
    nuevoVigente: 52451,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 295,
    descripcion: "ÚTILES MENORES, SUMINISTROS E INSTRUMENTAL MÉDICO-QUIRÚRGICOS, DE LABORATORIO Y CUIDADO DE LA SALUD",
    subProducto: "001-004-0004",
    nuevoVigente: 1010,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 295,
    descripcion: "ÚTILES MENORES, SUMINISTROS E INSTRUMENTAL MÉDICO-QUIRÚRGICOS, DE LABORATORIO Y CUIDADO DE LA SALUD",
    subProducto: "001-005-0001",
    nuevoVigente: 2295,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 295,
    descripcion: "ÚTILES MENORES, SUMINISTROS E INSTRUMENTAL MÉDICO-QUIRÚRGICOS, DE LABORATORIO Y CUIDADO DE LA SALUD",
    subProducto: "001-005-0003",
    nuevoVigente: 1262,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 295,
    descripcion: "ÚTILES MENORES, SUMINISTROS E INSTRUMENTAL MÉDICO-QUIRÚRGICOS, DE LABORATORIO Y CUIDADO DE LA SALUD",
    subProducto: "001-010-0001",
    nuevoVigente: 249,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 295,
    descripcion: "ÚTILES MENORES, SUMINISTROS E INSTRUMENTAL MÉDICO-QUIRÚRGICOS, DE LABORATORIO Y CUIDADO DE LA SALUD",
    subProducto: "001-012-0001",
    nuevoVigente: 470,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 295,
    descripcion: "ÚTILES MENORES, SUMINISTROS E INSTRUMENTAL MÉDICO-QUIRÚRGICOS, DE LABORATORIO Y CUIDADO DE LA SALUD",
    subProducto: "001-012-0002",
    nuevoVigente: 418,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 295,
    descripcion: "ÚTILES MENORES, SUMINISTROS E INSTRUMENTAL MÉDICO-QUIRÚRGICOS, DE LABORATORIO Y CUIDADO DE LA SALUD",
    subProducto: "001-013-0001",
    nuevoVigente: 518,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 295,
    descripcion: "ÚTILES MENORES, SUMINISTROS E INSTRUMENTAL MÉDICO-QUIRÚRGICOS, DE LABORATORIO Y CUIDADO DE LA SALUD",
    subProducto: "001-013-0002",
    nuevoVigente: 226,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 295,
    descripcion: "ÚTILES MENORES, SUMINISTROS E INSTRUMENTAL MÉDICO-QUIRÚRGICOS, DE LABORATORIO Y CUIDADO DE LA SALUD",
    subProducto: "001-019-0001",
    nuevoVigente: 22641,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 295,
    descripcion: "ÚTILES MENORES, SUMINISTROS E INSTRUMENTAL MÉDICO-QUIRÚRGICOS, DE LABORATORIO Y CUIDADO DE LA SALUD",
    subProducto: "001-020-0001",
    nuevoVigente: 301,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 295,
    descripcion: "ÚTILES MENORES, SUMINISTROS E INSTRUMENTAL MÉDICO-QUIRÚRGICOS, DE LABORATORIO Y CUIDADO DE LA SALUD",
    subProducto: "003-005-0001",
    nuevoVigente: 120,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 296,
    descripcion: "ÚTILES DE COCINA Y COMEDOR",
    subProducto: "001-001-0001",
    nuevoVigente: 9000,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 297,
    descripcion: "MATERIALES, PRODUCTOS Y ACCS. ELÉCTRICOS, CABLEADO ESTRUCTURADO DE REDES INFORMÁTICAS Y TELEFÓNICAS",
    subProducto: "001-001-0001",
    nuevoVigente: 4300,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 298,
    descripcion: "ACCESORIOS Y REPUESTOS EN GENERAL",
    subProducto: "001-004-0001",
    nuevoVigente: 18517,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 298,
    descripcion: "ACCESORIOS Y REPUESTOS EN GENERAL",
    subProducto: "001-019-0001",
    nuevoVigente: 1495,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 299,
    descripcion: "OTROS MATERIALES Y SUMINISTROS",
    subProducto: "001-001-0001",
    nuevoVigente: 28000,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 322,
    descripcion: "MOBILIARIO Y EQUIPO DE OFICINA",
    subProducto: "001-001-0001",
    nuevoVigente: 482564,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 323,
    descripcion: "MOBILIARIO Y EQUIPO MÉDICO-SANITARIO Y DE LABORATORIO",
    subProducto: "001-001-0001",
    nuevoVigente: 229830,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 324,
    descripcion: "EQUIPO EDUCACIONAL, CULTURAL Y RECREATIVO",
    subProducto: "001-001-0001",
    nuevoVigente: 55500,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 326,
    descripcion: "EQUIPO PARA COMUNICACIONES",
    subProducto: "001-001-0001",
    nuevoVigente: 125000,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 328,
    descripcion: "EQUIPO DE CÓMPUTO",
    subProducto: "001-001-0001",
    nuevoVigente: 411500,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
  {
    renglon: 329,
    descripcion: "OTRAS MAQUINARIAS Y EQUIPOS",
    subProducto: "001-001-0001",
    nuevoVigente: 776322,
    modificacionesIngru: 0,
    modificacionesNormal: 0,
    ejecucionNormal: 0,
    ejecucionRegularizado: 0,
    programadoNormal: 0,
    programadoRegularizado: 0,
    saldoProgramadoNormal: 0,
    saldoProgramadoRegularizado: 0,
  },
];
