export const PROGRAMACION_DATA = [
  {
    renglon: 111,
    descripcion: "ENERG\u00cdA EL\u00c9CTRICA",
    subProducto: "001-001-0001",
    presupuestario: 21000,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 112,
    descripcion: "AGUA",
    subProducto: "001-001-0001",
    presupuestario: 350,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 113,
    descripcion: "TELEFON\u00cdA",
    subProducto: "001-001-0001",
    presupuestario: 39172,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 114,
    descripcion: "CORREOS Y TEL\u00c9GRAFOS",
    subProducto: "001-001-0001",
    presupuestario: 1600,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 115,
    descripcion: "EXTRACCI\u00d3N DE BASURA Y DESTRUCCI\u00d3N DE DESECHOS S\u00d3LIDOS",
    subProducto: "001-001-0001",
    presupuestario: 1992,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 122,
    descripcion: "IMPRESI\u00d3N, ENCUADERNACI\u00d3N Y REPRODUCCI\u00d3N",
    subProducto: "001-001-0001",
    presupuestario: 2000,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 133,
    descripcion: "VI\u00c1TICOS EN EL INTERIOR",
    subProducto: "001-001-0001",
    presupuestario: 40000,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 135,
    descripcion: "OTROS VI\u00c1TICOS Y GASTOS CONEXOS",
    subProducto: "001-001-0001",
    presupuestario: 30000,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 141,
    descripcion: "TRANSPORTE DE PERSONAS",
    subProducto: "001-001-0001",
    presupuestario: 30000,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 151,
    descripcion: "ARRENDAMIENTO DE EDIFICIOS Y LOCALES",
    subProducto: "001-001-0001",
    presupuestario: 175000,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 157,
    descripcion: "ARRENDAMIENTO DE EQUIPO DE C\u00d3MPUTO",
    subProducto: "001-001-0001",
    presupuestario: 28125,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 158,
    descripcion: "DERECHOS DE BIENES INTANGIBLES",
    subProducto: "001-001-0001",
    presupuestario: 181911,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 171,
    descripcion: "MANTENIMIENTO Y REPARACI\u00d3N DE EDIFICIOS",
    subProducto: "001-001-0001",
    presupuestario: 360000,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 174,
    descripcion: "MANTENIMIENTO Y REPARACI\u00d3N DE INSTALACIONES",
    subProducto: "001-001-0001",
    presupuestario: 290000,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 182,
    descripcion: "SERVICIOS M\u00c9DICO-SANITARIOS",
    subProducto: "001-003-0001",
    presupuestario: 47000,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 182,
    descripcion: "SERVICIOS M\u00c9DICO-SANITARIOS",
    subProducto: "001-003-0005",
    presupuestario: 18000,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 182,
    descripcion: "SERVICIOS M\u00c9DICO-SANITARIOS",
    subProducto: "001-004-0001",
    presupuestario: 760074,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 182,
    descripcion: "SERVICIOS M\u00c9DICO-SANITARIOS",
    subProducto: "001-004-0004",
    presupuestario: 128795,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 182,
    descripcion: "SERVICIOS M\u00c9DICO-SANITARIOS",
    subProducto: "001-005-0001",
    presupuestario: 14705,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 182,
    descripcion: "SERVICIOS M\u00c9DICO-SANITARIOS",
    subProducto: "001-005-0003",
    presupuestario: 7001,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 182,
    descripcion: "SERVICIOS M\u00c9DICO-SANITARIOS",
    subProducto: "001-008-0002",
    presupuestario: 7200,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 182,
    descripcion: "SERVICIOS M\u00c9DICO-SANITARIOS",
    subProducto: "001-008-0003",
    presupuestario: 11200,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 182,
    descripcion: "SERVICIOS M\u00c9DICO-SANITARIOS",
    subProducto: "001-008-0004",
    presupuestario: 28000,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 182,
    descripcion: "SERVICIOS M\u00c9DICO-SANITARIOS",
    subProducto: "001-010-0001",
    presupuestario: 9794,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 182,
    descripcion: "SERVICIOS M\u00c9DICO-SANITARIOS",
    subProducto: "001-018-0001",
    presupuestario: 6000,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 182,
    descripcion: "SERVICIOS M\u00c9DICO-SANITARIOS",
    subProducto: "001-019-0001",
    presupuestario: 200637,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 182,
    descripcion: "SERVICIOS M\u00c9DICO-SANITARIOS",
    subProducto: "001-020-0001",
    presupuestario: 9774,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 182,
    descripcion: "SERVICIOS M\u00c9DICO-SANITARIOS",
    subProducto: "003-005-0004",
    presupuestario: 60452,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 186,
    descripcion: "SERVICIOS DE INFORM\u00c1TICA Y SISTEMAS COMPUTARIZADOS",
    subProducto: "001-001-0001",
    presupuestario: 80357,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 189,
    descripcion: "OTROS ESTUDIOS Y/O SERVICIOS",
    subProducto: "001-001-0001",
    presupuestario: 80357,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 199,
    descripcion: "OTROS SERVICIOS",
    subProducto: "001-001-0001",
    presupuestario: 22185,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 211,
    descripcion: "ALIMENTOS PARA PERSONAS",
    subProducto: "001-001-0001",
    presupuestario: 1500,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 211,
    descripcion: "ALIMENTOS PARA PERSONAS",
    subProducto: "001-004-0001",
    presupuestario: 5600,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 211,
    descripcion: "ALIMENTOS PARA PERSONAS",
    subProducto: "001-004-0004",
    presupuestario: 900,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 211,
    descripcion: "ALIMENTOS PARA PERSONAS",
    subProducto: "001-019-0001",
    presupuestario: 5600,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 211,
    descripcion: "ALIMENTOS PARA PERSONAS",
    subProducto: "003-005-0001",
    presupuestario: 900,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 211,
    descripcion: "ALIMENTOS PARA PERSONAS",
    subProducto: "003-005-0004",
    presupuestario: 4880,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 233,
    descripcion: "PRENDAS DE VESTIR",
    subProducto: "001-001-0001",
    presupuestario: 10860,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 241,
    descripcion: "PAPEL DE ESCRITORIO",
    subProducto: "001-001-0001",
    presupuestario: 4900,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 242,
    descripcion: "PAPELES COMERCIALES, CARTULINAS, CARTONES Y OTROS",
    subProducto: "001-005-0001",
    presupuestario: 500,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 242,
    descripcion: "PAPELES COMERCIALES, CARTULINAS, CARTONES Y OTROS",
    subProducto: "001-019-0001",
    presupuestario: 250,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 243,
    descripcion: "PRODUCTOS DE PAPEL O CART\u00d3N",
    subProducto: "001-001-0001",
    presupuestario: 6336,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 244,
    descripcion: "PRODUCTOS DE ARTES GR\u00c1FICAS",
    subProducto: "001-001-0001",
    presupuestario: 3909,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 247,
    descripcion: "ESPECIES TIMBRADAS Y VALORES",
    subProducto: "001-001-0001",
    presupuestario: 300,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 252,
    descripcion: "ART\u00cdCULOS DE CUERO",
    subProducto: "001-001-0001",
    presupuestario: 1566,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 261,
    descripcion: "ELEMENTOS Y COMPUESTOS QU\u00cdMICOS",
    subProducto: "001-001-0001",
    presupuestario: 3250,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 261,
    descripcion: "ELEMENTOS Y COMPUESTOS QU\u00cdMICOS",
    subProducto: "001-004-0001",
    presupuestario: 148,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 261,
    descripcion: "ELEMENTOS Y COMPUESTOS QU\u00cdMICOS",
    subProducto: "001-005-0001",
    presupuestario: 18,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 261,
    descripcion: "ELEMENTOS Y COMPUESTOS QU\u00cdMICOS",
    subProducto: "001-005-0003",
    presupuestario: 18,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 261,
    descripcion: "ELEMENTOS Y COMPUESTOS QU\u00cdMICOS",
    subProducto: "001-010-0001",
    presupuestario: 9,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 261,
    descripcion: "ELEMENTOS Y COMPUESTOS QU\u00cdMICOS",
    subProducto: "001-013-0001",
    presupuestario: 9,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 261,
    descripcion: "ELEMENTOS Y COMPUESTOS QU\u00cdMICOS",
    subProducto: "001-013-0002",
    presupuestario: 9,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 261,
    descripcion: "ELEMENTOS Y COMPUESTOS QU\u00cdMICOS",
    subProducto: "001-019-0001",
    presupuestario: 148,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 261,
    descripcion: "ELEMENTOS Y COMPUESTOS QU\u00cdMICOS",
    subProducto: "001-020-0001",
    presupuestario: 9,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 262,
    descripcion: "COMBUSTIBLES Y LUBRICANTES",
    subProducto: "001-001-0001",
    presupuestario: 1200,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 266,
    descripcion: "PRODUCTOS MEDICINALES Y FARMAC\u00c9UTICOS",
    subProducto: "001-004-0001",
    presupuestario: 436777,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 266,
    descripcion: "PRODUCTOS MEDICINALES Y FARMAC\u00c9UTICOS",
    subProducto: "001-004-0004",
    presupuestario: 14690,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 266,
    descripcion: "PRODUCTOS MEDICINALES Y FARMAC\u00c9UTICOS",
    subProducto: "001-005-0001",
    presupuestario: 11950,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 266,
    descripcion: "PRODUCTOS MEDICINALES Y FARMAC\u00c9UTICOS",
    subProducto: "001-005-0003",
    presupuestario: 3957,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 266,
    descripcion: "PRODUCTOS MEDICINALES Y FARMAC\u00c9UTICOS",
    subProducto: "001-010-0001",
    presupuestario: 1280,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 266,
    descripcion: "PRODUCTOS MEDICINALES Y FARMAC\u00c9UTICOS",
    subProducto: "001-012-0001",
    presupuestario: 2850,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 266,
    descripcion: "PRODUCTOS MEDICINALES Y FARMAC\u00c9UTICOS",
    subProducto: "001-012-0002",
    presupuestario: 128,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 266,
    descripcion: "PRODUCTOS MEDICINALES Y FARMAC\u00c9UTICOS",
    subProducto: "001-013-0001",
    presupuestario: 1978,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 266,
    descripcion: "PRODUCTOS MEDICINALES Y FARMAC\u00c9UTICOS",
    subProducto: "001-013-0002",
    presupuestario: 768,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 266,
    descripcion: "PRODUCTOS MEDICINALES Y FARMAC\u00c9UTICOS",
    subProducto: "001-019-0001",
    presupuestario: 279651,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 266,
    descripcion: "PRODUCTOS MEDICINALES Y FARMAC\u00c9UTICOS",
    subProducto: "001-020-0001",
    presupuestario: 1520,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 266,
    descripcion: "PRODUCTOS MEDICINALES Y FARMAC\u00c9UTICOS",
    subProducto: "003-005-0001",
    presupuestario: 6288,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 266,
    descripcion: "PRODUCTOS MEDICINALES Y FARMAC\u00c9UTICOS",
    subProducto: "003-005-0002",
    presupuestario: 580,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 266,
    descripcion: "PRODUCTOS MEDICINALES Y FARMAC\u00c9UTICOS",
    subProducto: "003-005-0004",
    presupuestario: 11080,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 267,
    descripcion: "TINTES, PINTURAS Y COLORANTES",
    subProducto: "001-001-0001",
    presupuestario: 22000,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 268,
    descripcion: "PRODUCTOS PL\u00c1STICOS, NYLON, VINIL Y P.V.C.",
    subProducto: "001-001-0001",
    presupuestario: 78195,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 269,
    descripcion: "OTROS PRODUCTOS QU\u00cdMICOS Y CONEXOS",
    subProducto: "001-001-0001",
    presupuestario: 800,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 283,
    descripcion: "PRODUCTOS DE METAL Y SUS ALEACIONES",
    subProducto: "001-001-0001",
    presupuestario: 600,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 289,
    descripcion: "OTROS PRODUCTOS MET\u00c1LICOS",
    subProducto: "001-001-0001",
    presupuestario: 13500,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 291,
    descripcion: "\u00daTILES DE OFICINA",
    subProducto: "001-001-0001",
    presupuestario: 28466,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 292,
    descripcion: "PRODUCTOS SANITARIOS, DE LIMPIEZA Y DE USO PERSONAL",
    subProducto: "001-001-0001",
    presupuestario: 9375,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 295,
    descripcion: "\u00daTILES MENORES, SUMINISTROS E INSTRUMENTAL M\u00c9DICO-QUIR\u00daRGICOS, DE LABORATORIO Y CUIDADO DE LA SALUD",
    subProducto: "001-004-0001",
    presupuestario: 52451,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 295,
    descripcion: "\u00daTILES MENORES, SUMINISTROS E INSTRUMENTAL M\u00c9DICO-QUIR\u00daRGICOS, DE LABORATORIO Y CUIDADO DE LA SALUD",
    subProducto: "001-004-0004",
    presupuestario: 1010,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 295,
    descripcion: "\u00daTILES MENORES, SUMINISTROS E INSTRUMENTAL M\u00c9DICO-QUIR\u00daRGICOS, DE LABORATORIO Y CUIDADO DE LA SALUD",
    subProducto: "001-005-0001",
    presupuestario: 2295,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 295,
    descripcion: "\u00daTILES MENORES, SUMINISTROS E INSTRUMENTAL M\u00c9DICO-QUIR\u00daRGICOS, DE LABORATORIO Y CUIDADO DE LA SALUD",
    subProducto: "001-005-0003",
    presupuestario: 1262,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 295,
    descripcion: "\u00daTILES MENORES, SUMINISTROS E INSTRUMENTAL M\u00c9DICO-QUIR\u00daRGICOS, DE LABORATORIO Y CUIDADO DE LA SALUD",
    subProducto: "001-010-0001",
    presupuestario: 249,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 295,
    descripcion: "\u00daTILES MENORES, SUMINISTROS E INSTRUMENTAL M\u00c9DICO-QUIR\u00daRGICOS, DE LABORATORIO Y CUIDADO DE LA SALUD",
    subProducto: "001-012-0001",
    presupuestario: 470,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 295,
    descripcion: "\u00daTILES MENORES, SUMINISTROS E INSTRUMENTAL M\u00c9DICO-QUIR\u00daRGICOS, DE LABORATORIO Y CUIDADO DE LA SALUD",
    subProducto: "001-012-0002",
    presupuestario: 418,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 295,
    descripcion: "\u00daTILES MENORES, SUMINISTROS E INSTRUMENTAL M\u00c9DICO-QUIR\u00daRGICOS, DE LABORATORIO Y CUIDADO DE LA SALUD",
    subProducto: "001-013-0001",
    presupuestario: 518,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 295,
    descripcion: "\u00daTILES MENORES, SUMINISTROS E INSTRUMENTAL M\u00c9DICO-QUIR\u00daRGICOS, DE LABORATORIO Y CUIDADO DE LA SALUD",
    subProducto: "001-013-0002",
    presupuestario: 226,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 295,
    descripcion: "\u00daTILES MENORES, SUMINISTROS E INSTRUMENTAL M\u00c9DICO-QUIR\u00daRGICOS, DE LABORATORIO Y CUIDADO DE LA SALUD",
    subProducto: "001-019-0001",
    presupuestario: 22641,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 295,
    descripcion: "\u00daTILES MENORES, SUMINISTROS E INSTRUMENTAL M\u00c9DICO-QUIR\u00daRGICOS, DE LABORATORIO Y CUIDADO DE LA SALUD",
    subProducto: "001-020-0001",
    presupuestario: 301,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 295,
    descripcion: "\u00daTILES MENORES, SUMINISTROS E INSTRUMENTAL M\u00c9DICO-QUIR\u00daRGICOS, DE LABORATORIO Y CUIDADO DE LA SALUD",
    subProducto: "003-005-0001",
    presupuestario: 120,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 296,
    descripcion: "\u00daTILES DE COCINA Y COMEDOR",
    subProducto: "001-001-0001",
    presupuestario: 9000,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 297,
    descripcion: "MATERIALES, PRODUCTOS Y ACCS. EL\u00c9CTRICOS, CABLEADO ESTRUCTURADO DE REDES INFORM\u00c1TICAS Y TELEF\u00d3NICAS",
    subProducto: "001-001-0001",
    presupuestario: 4300,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 298,
    descripcion: "ACCESORIOS Y REPUESTOS EN GENERAL",
    subProducto: "001-004-0001",
    presupuestario: 18517,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 298,
    descripcion: "ACCESORIOS Y REPUESTOS EN GENERAL",
    subProducto: "001-019-0001",
    presupuestario: 1495,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 299,
    descripcion: "OTROS MATERIALES Y SUMINISTROS",
    subProducto: "001-001-0001",
    presupuestario: 28000,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 322,
    descripcion: "MOBILIARIO Y EQUIPO DE OFICINA",
    subProducto: "001-001-0001",
    presupuestario: 482564,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 323,
    descripcion: "MOBILIARIO Y EQUIPO M\u00c9DICO-SANITARIO Y DE LABORATORIO",
    subProducto: "001-001-0001",
    presupuestario: 229830,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 324,
    descripcion: "EQUIPO EDUCACIONAL, CULTURAL Y RECREATIVO",
    subProducto: "001-001-0001",
    presupuestario: 55500,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 326,
    descripcion: "EQUIPO PARA COMUNICACIONES",
    subProducto: "001-001-0001",
    presupuestario: 125000,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 328,
    descripcion: "EQUIPO DE C\u00d3MPUTO",
    subProducto: "001-001-0001",
    presupuestario: 411500,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  },
  {
    renglon: 329,
    descripcion: "OTRAS MAQUINARIAS Y EQUIPOS",
    subProducto: "001-001-0001",
    presupuestario: 776322,
    septiembre_normal: 0,
    septiembre_regularizado: 0,
    octubre_normal: 0,
    octubre_regularizado: 0,
    noviembre_normal: 0,
    noviembre_regularizado: 0,
    diciembre_normal: 0,
    diciembre_regularizado: 0,
    total_normal: 0,
    total_regularizado: 0,
    saldo: 0,
  }
];
